# Generated by Django 5.0.4 on 2024-05-09 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0004_coursesubscription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursesubscription',
            old_name='owner',
            new_name='user',
        ),
    ]
